### ISSUE TITLE
这个2 从哪里来的？

### ISSUE THREAD

**Issue by spjnt** [guolindev/LitePal#400]
代码  ：    List<UpHistory> all = LitePal.findAll(UpHistory.class);
        if (all != null && all.size() > 0) LitePal.deleteAll(UpHistory.class);
        for (int i = 0; i < 100; i++) {
            UpHistory history = new UpHistory();
            history.setCode(i + "");
            history.setUp_time(TimeUtil.getNowTime());
            history.save();
        }
        List<UpHistory> songs = LitePal.where("code > ? and code < ?", "10", "20").find(UpHistory.class);
        for (int i = 0; i < songs.size(); i++) {
            Log.e("测试", songs.get(i).getCode() + "");
        }

日志  E/测试: 2，11， 12，13， 14，15，16，17，18，19

**Comment by guolindev** [comment]
稀奇了，我也从来没有遇到过这个问题，LitePal的查询也是在SQLiteDatabase基础上进行的封装，建议你可以使用最原始的查询方式来执行一下同样的查询，看看会不会有这样的问题。

**Comment by xiexin52k** [comment]
你试试将Code的数据类型变成int, 不要用String
