### ISSUE TITLE
希望LitePal可以添加索引功能

### ISSUE THREAD

**Issue by baojianfeng** [guolindev/LitePal#618]
郭神，很感谢你为大家带来如此好的开源作品，事务终于可以用了，但是抱歉我又是来提需求的，我们现在的项目数据量慢慢增大，查询操作时间有点长了。目前所知LitePal还不支持索引，所以希望郭神更扩展一下功能。

**Comment by guolindev** [comment]
索引这个功能我之前其实加过一次，后来中途应该是遇到了什么困难，最后又放弃了。

这个功能我确实也计划在接下来的版本中提供，不过因为有上次失败的记忆，可能不一定会那么顺利，需要点时间。

**Comment by baojianfeng** [comment]
好的，郭神，大家相信你一定能搞定的，加油大佬！

**Comment by wangning08115** [comment]
索引问题是不是可以通过开放一个    较为原生的sqlite操作接口 来自行给数据库加入索引呢？

**Comment by guolindev** [comment]
3.2.0版本已支持索引功能，具体请参考文章 https://blog.csdn.net/guolin_blog/article/details/107744242
