### ISSUE TITLE
直接读取外部数据库

### ISSUE THREAD

**Issue by 2372281891** [guolindev/LitePal#635]
郭神，这是我在搞一个app的时候想到的一个功能。

功能场景如下：
我在**APP_1**通过litepal创建了一个数据库1.db，并且是经过litepal自带的aes加密过的，秘钥为github。

现在我想在**APP_2**的assets文件夹放入1.db，且APP_2能通过litepal直接读取这个db文件，**即使APP_2自建数据库时使用的秘钥不是“github”**。

假设一个读取方法：
`LitePal.readExternal("path" + 1.db).byKey("github");`

**Comment by guolindev** [comment]
LitePal后面会更加关注易用性和架构设计，像这种不是太常用的功能LitePal短期内可能不会考虑支持了。

另外LitePal在不久的版本之后会禁用加载sd卡上的数据库文件的功能，合理做减少，只保留真正必要的功能是我接下来重点要考虑的事情。
