### ISSUE TITLE
litepal.exceptions.LitePalSupportException: Save current model failed.

### ISSUE THREAD

**Issue by popmj007** [guolindev/LitePal#637]
app和moulle里面都有litepal.xml，找不到app里面需要的表

**Comment by guolindev** [comment]
module里不需要配litepal.xml，只要在app里配置就可以了。

**Comment by hechunjiang** [comment]
> module里不需要配litepal.xml，只要在app里配置就可以了。

如果是以jar包 或者 依赖的方式引入呢

**Comment by Arsun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
