### ISSUE TITLE
请问litepal内存创建了对象复用池吗?

### ISSUE THREAD

**Issue by SJLBenjamin** [guolindev/LitePal#639]
在查询的时候每次都会返回一个集合,因为数据量比较大,想加快查询速度,减少内存抖动,请问这个集合里面的对象是每次都重新创建吗还是存在复用机制

**Comment by guolindev** [comment]
并没有复用机制，因为LitePal查询出来的对象可能是任意类型。而且数据量也不固定，可多可少，所以很难去设置一个对象复用池的大小，设大了浪费内存，设小了又起不到作用，所以对象复用池不太适合LitePal框架。

**Comment by SJLBenjamin** [comment]
可以提供接口让外部调用吗
