### ISSUE TITLE
Can't instantiate abstract class android.content.Context

### ISSUE THREAD

**Issue by yilylong** [guolindev/LitePal#640]
类里面有个context属性  我已经加了 ignore 注解：
@Column(ignore = true)
    private Context context;

在查询的时候，反射对象的时候报错了。我看了表里没这个字段 为什么还会反射生成呢
难道构造函数传入有影响？

**Comment by yilylong** [comment]
跟了下代码因为在构造函数中使用了Context 在反射生成Context的时候出报了这个错（无法反射抽象类？），看来我只有改造我的构造函数不要传Context了。

**Comment by guolindev** [comment]
@column(ignore = true)属性肯定是可以生效的，但是你把Context加在构造函数上面，那就无法生效了，因为LitePal要通过你的构造函数来创建实例。
