### ISSUE TITLE
郭神，能否比较一下 Litepal 和 Room 两个 ORM 框架有什么不同的特点？

### ISSUE THREAD

**Issue by gs666** [guolindev/LitePal#641]
以前在项目中应用到简单的数据库操作，都会使用 Litepal。最近学习了 Jetpack 的 Room 库，发现也非常好用。我只是普通的开发者，对两个库的具体实现原理和适合的开发场景并不清楚。郭神能否介绍一下两者的特点和使用场景呢？

**Comment by guolindev** [comment]
这两个库的差别点非常大，反而相似点很少，所以让我比较的话，我可能能比较出一大堆东西。

1.
LitePal的API设计比较受ActiveRecord的影响，在数据库接口方面注重的是调用的简易性。
Room的API设计比较受Retrofit的影响，不提供便捷的数据库接口调用，更注重的整体App架构的设计。

2.
LitePal在尽可能地让开发者不写SQL，为此提供了一系列的便捷API。
Room需要开发者写很多SQL，但都以注解的形式封装到了DAO函数上面，这样当开发者调用函数时其实就是在执行SQL。

3.
LitePal几乎不依赖于注解，少数注解也是用的运行时注解，功能比较简单。
Room高度依赖于注解，并且是通过编译时注解生成代码，性能更高。

4.
LitePal提供了非常使得的表管理功能，升级表完全自动化，开发者只需要改一下版本号即可。
Room的表升级简直是噩梦，完全需要自己手动表升级语句，出错率极高。（因为第一代表是Room自动生成的，后续升级的话需要手写SQL语句，但是升级的SQL要和第一代表的结构完全一致，这块不用心写非常容易出错）

5.
Room不提供异步操作接口，但是要求所有数据库操作在IO线程中进行。但是新版Room已支持协程，简化了异步的操作。
LitePal虽然提供了异步接口，但是在最新版本中已废弃，准备接下来参考Room，支持协程。

其他区别还有很多很多，我就不一一列举了。

总体上来说，Room的设计比较精简，非常清晰地告诉你我就三块东西，Database、Dao、Model，这些功能就够你用的了。

而LitePal可能是因为历史原因吧，设计比较庞大，表管理系统就是一大块，另外还有增删改查，聚合函数等等功能，这些在Room看来都是不会提供的，给你一个@Query注解就都能解决了，SQL语句自己去写吧。

LitePal我会一直维护下去，另外Room确实有很多设计得比较出色且值得借鉴的地方，我准备在接下来的几个版本中慢慢加进去。但是反过来，Room肯定是不会参考LitePal的，虽然我真的觉得Room的表升级方面得好好简化一下。

**Comment by gs666** [comment]
感谢郭神的解答，对于第四条我真是不能赞同更多。前不久刚踩过这个坑，因为我数据库增加了一个字段，升级需要写 sql 新增列语句，平时只写CRUD的我写错了好多回。不写对的话，程序跑起来直接就 crash 了。

**Comment by guolindev** [comment]
打了这么多字，我都不舍得把这个issue关掉了，先放段时间吧，如果有其他开发者对这个问题也比较关注的可以参考一下。

**Comment by shusheng007** [comment]
刚接触room不久，还没有深入去看，以下是我的几点浅薄的看法：
- room 通过设置`allowMainThreadQueries()` 是允许在main线程执行的。
- room 更像mybatis，这种半自动化ORM的方式，使得其灵活性更高，但是对小白不太友好。
- room 不仅集成了谐程，而且可以结合rxjava，livedata 等一起使用。
- room 还是google 官方出品，后续维护更新更加有保障

总的来说，如果你在为一个商业性的App选择ORM框架，毫无疑问应该选择room。如果是自己使用，那就看你心情了，Litepal应该也挺好。

**Comment by acloudtwei** [comment]
第一次看这个ORM框架，没想到是郭神的作品！

不得不说ROOM的升级真的挺麻烦的，没有LitePal这么简单。
不过ROOM确实很像Mybatis，但是结合RxJava的话有好也有坏吧。

**Comment by Arsun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
