### ISSUE TITLE
郭神，可否执行事务返回事务是否成功

### ISSUE THREAD

**Issue by HAHH9527** [guolindev/LitePal#643]
像这样
```kotlin
val succeeded = LitePal.runInTransaction {
    val result1 = // 数据库操作1
    val result2 = // 数据库操作2
    val result3 = // 数据库操作3
    result1 && result2 && result3
}

if (succeeded) {
    //成功后操作
} else {
    //失败后操作
}
```

不知这样是否合理

具体修改文件路径应该是在
/core/src/main/java/org/litepal/extension/LitePal.kt
628行

**Comment by guolindev** [comment]
挺好的建议，正好LitePal很快就要出下个版本了，我会在下个版本里面针对这个API加入返回值，多谢提出。

**Comment by guolindev** [comment]
LitePal 3.2.1版本中已加入runInTransaction的返回值，可参考这条提交 https://github.com/guolindev/LitePal/commit/4cf3c68dfc16479846c9f5d0879018f163d9dbf4
感谢建议。
