### ISSUE TITLE
提问：数据表中的数据更新  使用save 不使用update 随后会导致用该表的id作为外键的表数据查询不到

### ISSUE THREAD

**Issue by qianyanxiang** [guolindev/LitePal#645]
两张表 Tch  Task  一对多

  Tch tch = tches.get(i);
            Tch databaseData = LitePal.where("bccbny =? and taskname=? and usercode=?", bccbny, tch.getTaskName(), user.getUserCode()).findFirst(Tch.class);
            if (databaseData != null) {
                List<Task> tasks = getTasks(databaseData);
                LogUtils.d("保存前的统册号" + tch.getTaskName() + "\n有" + tasks.size() + "条任务");
                databaseData.setBccbny(bccbny);
                databaseData.setMeterNumber(tch.getMeterNumber());
//                databaseData.update(databaseData.getId());
                databaseData.save();
                List<Task> tasks1 = getTasks(databaseData);
                LogUtils.d("保存后的统册号" + tch.getTaskName() + "\n有" + tasks1.size() + "条任务");
            } else {
                tch.setUserCode(user.getUserCode());
                tch.setBccbny(bccbny);
                tch.save();
            }
使用   databaseData.save();会导致save之后查询的Task列表数据长度为0 
使用  databaseData.update(databaseData.getId())
使用save的日志：
![image](https://user-images.githubusercontent.com/20348560/89479052-6bc73280-d7c4-11ea-9ca2-84585438a32b.png)
使用update的图片：
![image](https://user-images.githubusercontent.com/20348560/89479206-cb254280-d7c4-11ea-9429-4f9771e8a59a.png)
是因为 用save去更新数据的话只能使用 find（Class<T>,id）这种查询出来的才可以吗？

**Comment by guolindev** [comment]
那是因为，你这里有表关联的情况，查询的时候只把当前Model的数据查出来了，关联的内容没查出来，这个时候重新save，LitePal为认为你想清除关联关系，所以所有的关联就都丢失了。

这种情况下正确的做法是查询的时候加个isEager属性，把关联数据也查出来，就不会丢失了。

当然，只用update更新必要的字段，可能是更加正确的做法。

**Comment by cai525** [comment]
实测加isEager有效，楼上说的对

**Comment by qianyanxiang** [comment]
checked。
