### ISSUE TITLE
在一对多的关联表中，多条评论属于某个新闻，如何找到某条评论所属的新闻？

### ISSUE THREAD

**Issue by qazxcs113** [guolindev/LitePal#651]
在关联表中，
如果我根据id去查询某条评论。
然后顺着想去找他是属于哪条新闻的，这个新闻的对象得出来是null.

有什么方法可以得到这条新闻的对象吗？

**Comment by qazxcs113** [comment]
举个栗子：
public class Sport_History_Table extends LitePalSupport {
 private int id;

    private Device_Table gDevice_Table ;         //外键
    private Sport_Mode_Table gSport_Mode_Table;          //外键
    private long Timestamp_start;
//...get,set方法我就不写了。
}
Sport_History_Table b = LitePal.find(Sport_History_Table.class,1);
                Log.d(TAG, "FindSport_HistoryTableByDeviceAddress: "+b.getSport_type());
输出为空

**Comment by guolindev** [comment]
关联表中的数据默认是不会加载出来的，因为考虑效率的因素。

如果你想加载出关联表的数据，可以使用激进查询，在find方法的最后加上一个true参数即可。

`Sport_History_Table b = LitePal.find(Sport_History_Table.class, 1, true);`
