### ISSUE TITLE
一个奇特的BUG,类B中存在外键，类A继承类B，然后用类A进行存储，外键对象无法存储。但普通对象可以。

### ISSUE THREAD

**Issue by qazxcs113** [guolindev/LitePal#652]
举个栗子：
public class Indicator extends LitePalSupport {
    protected int id;

    protected Sport_Mode_Table gSport_Mode_Table = new Sport_Mode_Table();//外键
    protected Device_Table gDevice_Table = new Device_Table();//外键
    protected float Value;
}
public class Indicator_Son extends Indicator {
}

//存储过程..
 Indicator_Consume_Table x = new Indicator_Consume_Table();
                    x.setgSport_Mode_Table(TemSport_Mode_Table);//TemSport_Mode_Table这个对象是从数据库中拿出来的某一条数据
                    x.setValue(10);
                    x.setgDevice_Table(TemDeviceTable);//同上
                     x.save();

版本：3.0
问题：
运行完后，查看数据库。两个外键的Sport_Mode_Table，Device_Table没有被存入。不知道为什么。
但是如果我Indicator_Son 不用继承，直接按父类直接复制过来。 那么我就存储这些外键了。。
想问一下怎么解决。  （主要是某些表字段是一模一样的，我就不用重复写了，查询的时候使用范类也可以偷懒~）

**Comment by qazxcs113** [comment]
试了很久，才来提问，问下有没有什么解决方法。。
最后试了一下。
举个栗子：

public class Indicator extends LitePalSupport {
protected int id;
protected float Value;
protected Sport_Mode_Table gSport_Mode_Table = new Sport_Mode_Table();//外键
protected Device_Table gDevice_Table = new Device_Table();//外键
...//get ,set 方法
}
public class Indicator_Son extends Indicator {
protected Sport_Mode_Table gSport_Mode_Table = new Sport_Mode_Table();//外键
protected Device_Table gDevice_Table = new Device_Table();//外键
...///get ,set 方法
}

将所有的外键放到子类去，当然父类也要存在同名的方法。。。
这样子就可以解决上面发现的事情了。。

大致推断一下为什么：
  因为外键是别的表的东西，而整个父类数据是跟这个关联表是没有任何关系的（因为这个只是数据的表现，加入到litepal.xml的是子类）
所以当你在外部对外键对象使用set方法的时候，是对父类进行赋值的。
而因为父类跟关联表没有关系，所以，就没办法存储了0 0.。。 
当然了这种说法说不通为什么普通类型的int , float类型之类的就可以存进去。。可能大概是普通数据类型本身就没有关联。所以可以存进去？。~

希望郭神可以帮忙看一下，如果有说不对的地方可以指正一下。

**Comment by guolindev** [comment]
这个情况我可能还没尝试过，或许在继承结构当中获取外键的逻辑部分有问题，我会找时间尽快检查一下，有了结果我会更新这个issue，感谢指出。

**Comment by guolindev** [comment]
这个问题我具体分析了一下，得出的结论是，用于建立关联关系的字段，如果去继承结构中找寻的话，可能会产生很多不在预期之内的问题。

比如Teacher和Student之间本身是多对多的关联关系，而如果抽象出了一个BaseTeacher和BaseStudent，我们仍然把关联关系保持在Teacher和Student中这样不会出现任何问题，但如果抽象到上一层就不好说了，因为如果BaseTeacher引用了Student的关联，而Student引用了BaseTeacher的关联，这样看上去就好像是BaseTeacher和Student建立了关联关系，把Teacher给架空了。这样多对多的中间表，或是多对一的外键，是使用BaseTeacher来建议还是使用Teacher来建立就不明确了。而如果是BaseTeacher引用了Student的关联，Student去引用Teacher的关联，这样在分析关联关系时也会出问题，因为本身是Teacher引用Student，Student引用Teacher，它们是多对多的关系，然而现在变成了BaseTeacher引用Student，Student引用Teacher，这看上去就变成三方关联的关系了，对于LitePal来说这样是很难分析的。

所以为了让问题简化，建议还是不要把关联关系的声明放到父类当中。
