### ISSUE TITLE
有关where查询中的in条件

### ISSUE THREAD

**Issue by Billyyanyz** [guolindev/LitePal#653]
在先前的issue中，博客上和教程中，有关在where查询中用in查询的方法都有些模糊，按照所有可能的格式提供字符串都无法找到，只能求助于大家了。
现在我有一个这样的查找：where("type in (?)", str)，这个str是我通过将list<String>中的对象拼接而成的。
那拼接完的str应该是哪一种样子:
`'type1','type2'`
`"type1","type2"`
`"type1,type2"`
`type1,type2`
还是这些格式都不对?

**Comment by guolindev** [comment]
sql语句中的in不是这样用的，而是"where type in('a', 'b', 'c', 'd')"这个样子的。

LitePal并不发明语句，只是做封装而已，所以你用litepal进行查询时，应该这样写where("type in (?, ?, ?, ?)", "a", "b", "c", "d")

具体要写几个占位符根据你的list而定，这个是要你自己组装的。
