### ISSUE TITLE
LitePalSupport--调用update()，更新状态失败

### ISSUE THREAD

**Issue by 0501fei** [guolindev/LitePal#655]
**在更新对象状态字段，调用update方法时，状态设置为0，数据库字段更新失败。** 
例如：
                    item.setState(0);
                    item.update(item.getId());
update() 方法返回值 为 1；但实际上并没执行成功。
郭神望解答。

**Comment by 0501fei** [comment]
> 在更新对象状态字段，调用update方法时，状态设置为0，数据库字段更新没有失败。
> 例如：
> item.setState(0);
> item.update(item.getId());
> update() 方法返回值 为 1；但实际上并没执行成功。

**Comment by guolindev** [comment]
重复问题，参考这条issue https://github.com/guolindev/LitePal/issues/32
