### ISSUE TITLE
请问郭神，如果某些情况下需要降级App，litepal的降级应该怎么做呢

### ISSUE THREAD

**Issue by herenxue** [guolindev/LitePal#657]

**Comment by guolindev** [comment]
LitePal没有降级功能，只可以升级。

其实我觉得你也可以理解成LitePal没有升级和降低功能，LitePal只是会把数据库和当前代码中的实体类进行同步。

所以，如果你想实现降级效果，把你的实体类修改成你想降级后的样子，然后在litepal.xml中升级版本号即可。

**Comment by herenxue** [comment]
项目中现在用到了你的litepal 我意思是加入某些特殊原因下需要应用降级安装(我们的是静默安装)，但是我发现litepal就会出现崩溃。假如在不更改代码重新打包的情况下，litepal有没有相关的操作能够实现降级？

**Comment by guolindev** [comment]
这个确实没办法，我从来没有考虑过这种需求。我这边也没有任何手法能够实现降级安装，所以也没办法对你说的现象进行测试。

**Comment by herenxue** [comment]
好的，确实是我们的比较特殊，如果版本有晋级问题，需要回退应用所以会出现需要降低安装的情况
