### ISSUE TITLE
updateAll()方法没有起到更新效果

### ISSUE THREAD

**Issue by QQQ01** [guolindev/LitePal#658]
在第一行代码第二版学习Litepal时,按照实例使用updateAll()方法数据没有更新,setPrice()和setPress()方法也没有生效.   
        Button updateData = findViewById(R.id.update_data);
        updateData.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Book book = new Book();
                book.setPrice(14.95);
                book.setPress("Anchor");
                book.updateAll("name = ? and author = ?","The Lost Symbol ","Dan Brown");
            }
        });

**Comment by guolindev** [comment]
updateAll()方法是有返回值的，返回值代表着有多少行数据受到了影响，你可以把返回值打印出来看一看，是不是0。

如果是0的话，那就说明0行数据受到影响，基本可以判断是你指定的where条件不对导致的。

**Comment by QQQ01** [comment]
> updateAll()方法是有返回值的，返回值代表着有多少行数据受到了影响，你可以把返回值打印出来看一看，是不是0。
> 
> 如果是0的话，那就说明0行数据受到影响，基本可以判断是你指定的where条件不对导致的。

**Comment by QQQ01** [comment]
> updateAll()方法是有返回值的，返回值代表着有多少行数据受到了影响，你可以把返回值打印出来看一看，是不是0。
> 
> 如果是0的话，那就说明0行数据受到影响，基本可以判断是你指定的where条件不对导致的。

我试了下,的确是0.不过我复制了郭神的源码还是这样啊......然后复制了下github示例里的...也不行呀....呜呜,updataAll()源码也看不栋...

**Comment by guolindev** [comment]
那你把issue关了干啥，问题还没解决。

如果是0的话，那就是没有更新任何数据，这种情况基本就是因为条件指定错了，或者数据库中本来就没有数据。

你可以试一下用相同的条件去查询一下数据，看看能不能查询到：

List<Book> books = LitePal.where("name = ? and author = ?","The Lost Symbol ","Dan Brown").find(Book.class);

然后打印一下看看books，看看它的size是不是0。

**Comment by QQQ01** [comment]
不小心误操作关了......
数据库里Book表的添加的数据是这个
![image](https://user-images.githubusercontent.com/52373880/94514806-bc06c200-0254-11eb-81fb-f455338e4bab.png)
List books = LitePal.where("name = ? and author = ?","The Lost Symbol ","Dan Brown").find(Book.class);
用这个查询,books的size是0

**Comment by guolindev** [comment]
你这数据和查询条件对应不上呀，查出来的结果肯定是0了。

你指定要查The Lost Symbol这本书，数据库里的书名却是The Da Vinci Code，这样肯定查询不到呀，当然也就无法更新了。

**Comment by QQQ01** [comment]
噢噢,知道了!!!感谢
