### ISSUE TITLE
如何在一个db数据库里面，用同一个类创建多张名字不一样的表格？

### ISSUE THREAD

**Issue by zhaohuan8799** [guolindev/LitePal#659]

**Comment by guolindev** [comment]
不好意思，这个功能litepal是不支持的。

**Comment by gzpaiwxc** [comment]
请问这种功能有哪种数据库框架是可以支持的呢?

**Comment by zhaohuan8799** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    自己写，把类与数据库操作绑定起来
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2021年12月27日 ***@***.***> 写道： 




请问这种功能有哪种数据库框架是可以支持的呢?
