### ISSUE TITLE
有没有清空数据库的方法只清空每一张表的数据 表结构不变

### ISSUE THREAD

**Issue by aglszz** [guolindev/LitePal#660]

**Comment by aglszz** [comment]
LitePal.deleteAll(WeatherLP.class);   只能这样一张一张的清空么  郭神

**Comment by guolindev** [comment]
对，这是最好的做法，也最安全，另外还有一种LitePal.deleteDatabase的方式，但是不太推荐使用，可能会存在一些安全隐患。
