### ISSUE TITLE
查询bug，有时候查询不到。

### ISSUE THREAD

**Issue by Moster1h** [guolindev/LitePal#661]
数据库中存在这一条数据，但是打开应用有时候可以查询得到，有时候查询不到。关键是查询的是用户的登录信息，导致有的用户已经登录了，但是关闭应用重新打开应用又需要登录，这导致很多用户说我窃取他们的信息，真的好坑，查询也是最简单的。
```
public LoginUserModel getSelectedLoginUser() {
        try {
            return LitePal.where("isSelected=1").findFirst(LoginUserModel.class);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
```
![image](https://user-images.githubusercontent.com/55750427/94359442-d700f700-00d9-11eb-8a63-aee7c480f3ea.png)

**Comment by guolindev** [comment]
我可以负责任地告诉你，LitePal的查询功能已经经历长达6年实践了，而且没有大改过，所以可以说是相当稳定。如果你出现有时能查询到，有时查询不到的情况，99%的可能性是你自己的用法有问题。

从你上面贴出的代码来看，你首先指定了一个where("isSelected=1")的条件，然后查询符合这个条件下的第一条记录，那么只有你的LoginUserModel这张表中存在isSelected=1的记录，才会返回对应这条记录的对象，否则就会返回null。所以当你出现查询不到的时候，我建议你看一下LoginUserModel这张表中是否存在isSelected=1的记录，然后再判断是否是LitePal的bug。

**Comment by guolindev** [comment]
你可以使用LitePal.findAll(LoginUserModel.class)试一试把整张表中的数据都查询出来，看一看里面的数据有没有isSelected是等于1的，我感觉还是因为条件指定的原因导致没能正常查询到数据，我按你写的这种场景又去做了下测试也都是正常的。

**Comment by Moster1h** [comment]
这个我已经找到原因了，在查询之前不能使用SharedPreferences的commit方法。你可以测试。我也可以给你测试的Demo

**Comment by guolindev** [comment]
表示不能理解，数据库的查询跟SharedPreferences有什么关系，如果你可以把测试demo提供给我最好，可以放到百度网盘里然后给我个链接吗？

**Comment by Moster1h** [comment]
具体原因不是很清楚，简单的demo无法复现。但是去掉那段sp的代码，就好了。没有去掉sp代码之前，大概十几次就有一次查询不到。

**Comment by guolindev** [comment]
那查询不到的这次，是单单where("isSelected=1")这个条件下查询不到，还是整张表的所有数据都查询不到？

**Comment by Moster1h** [comment]
这个没有尝试过，不过我去掉了sp的那段代码之后，就好了。这个问题有必要关吗？

**Comment by guolindev** [comment]
不知道啊，因为你说的这个情况太玄乎了，我甚至不能判断这是不是一个系统的bug。

既然这个bug不会再出现，那么我就先把这个issue关掉了，如果你又可以重现这个bug了，那么请再把这个issue打开吧。
