### ISSUE TITLE
Can't determine type for tag

### ISSUE THREAD

**Issue by Deepblue1996** [guolindev/LitePal#664]
litepal.xml 放在 assets 中一直提示这个，放在xml就不提示了，换了几个AS版本都一样

**Comment by guolindev** [comment]
帮你在网上搞了个相关的解答，一般是因为你的litepal.xml文件格式有问题才会这样。

https://stackoverflow.com/questions/57984036/getting-an-cant-determine-type-for-tag-on-android-studio#:~:text=This%20type%20of%20error%20is,the%20error%20will%20be%20gone.

建议你可以复制litepal源码demo中的litepal.xml文件过去做修改，这样可以保证格式是没有问题的。

**Comment by Deepblue1996** [comment]
位置问题，我放在res文件夹下，放错位置
