### ISSUE TITLE
如何修改日期格式数据

### ISSUE THREAD

**Issue by pengfalin** [guolindev/LitePal#665]
在有些需要记录日期格式的数据，如何在当前表中更新日期格式数据

**Comment by xiexin52k** [comment]
那干嘛不直接将日期格式化好放进去呢? 或者只存日期毫秒数, 使用的时候将他转换成你要的格式岂不是更加灵活一些吗?

**Comment by guolindev** [comment]
LitePal支持存储Date类型的数据，在数据库中是以毫秒值自动映射的。你如果要改新日志，只需要更新你的模型中的date对象，重新dave到数据库的时候会自动更新存储的毫秒值。
