### ISSUE TITLE
郭大大，能追加个unique相同的情况下自动覆盖更新而不是报异常么

### ISSUE THREAD

**Issue by DonkeyTomy** [guolindev/LitePal#667]
比如联系人，号码是唯一的，我如果将更改某个号码下的别的信息，那么只需要在将修改后的信息再保存一遍，在保存的时候检测到已有该号码，不会报异常取消，而是去更新该数据。就相当于把unique作为id去查找，或者定义个新属性，有相同的就更新。我记得之前Room是有这个操作的，现在用LitePal就得每次调用where操作，挺繁琐的。或者说现在LitePal支持这个操作么，请大大指导下。

**Comment by xiexin52k** [comment]
原始数据库对于unique就是这样处理的. 
你自己可以重写他的saveOrUpdate()函数嘛, 
我自己举个例子给你看, 
```java
  public boolean saveOrUpdate() {
        return super.saveOrUpdate("filePath=?", this.filePath);
    }
```
这个代码"filePath"也是unique的. 但是我保存并更新将他封装好了. 这样我在其他地方就不用每次都要写条件了. 直接调用你重写的saveOrUpdate就行了

**Comment by guolindev** [comment]
Room的设计是这个样子的，如果你向数据中重复插入了同一个对象，那么默认会抛出异常，当然你可以配置OnConflictStrategy来指定你想要的行为，比如说覆盖原有数据。

LitePal本身就是支持更新一个已存储的对象的，也就是说，不管你怎么重复存储同一个对象，LitePal都不会报错，而是会更新数据库里的数据，和Room当中的OnConflictStrategy.REPLACE是类似的效果。

但如果你不是重复存储同一个对象，而是根据某个字段是否已存储来决定是更新还是插入，这个就得通过逻辑判断来实现了，比如说先查询是否存在，然后插入或才更新，或者也可以使用 @xiexin52k 提供的方案，使用saveOrUpdate()函数来解决。

**Comment by zhuzhutai** [comment]
> 改某个号码下的别的信息，那么只需要在将修改后的信息再保存一遍，在保存的时候检测到已有该号码，不会报异常取消，而是去更新该数据。就相当于把unique作为id去查找，或者定义个新属性，有相同的就更新。我记得之前Room是有这个操作的，现在用LitePal就得每次调用where操作，挺繁琐的。或者说现在LitePal支持这个操作么，请大大指导下

我懂你的意思；重写你要存储的对象 equals 方法即可,这样存储直接就是更新内容了。

@Column(unique = true)
var phoneNum: String = ""

override fun equals(other: Any?): Boolean {
            if (other.phoneNum == phoneNum)
                return true
        return false
}
