### ISSUE TITLE
结构体嵌套结构体数组，怎么处理，有例子么？

### ISSUE THREAD

**Issue by hustbind** [guolindev/LitePal#668]
结构体嵌套结构体数组，怎么处理，有例子么？

**Comment by hustbind** [comment]
public class SubjectResults extends LitePalSupport {
    //private long id;
    @Column(unique = true)
    long pointID;

    List<SubjectResult> results = new ArrayList<SubjectResult>();
    …………
}

public class SubjectResult extends LitePalSupport {

    public SubjectResult() {
        this.Answer = "";
        this.Answer_des = "";
    }
    long pointID;

    SubjectResults subjectResults;

    @Column(defaultValue = "")
    String Project_id;

    @Column(defaultValue = "")
    String Answer;

    @Column(defaultValue = "")
    String Answer_des;

    List<String> Photo_list = new ArrayList<String>();
    List<String> Video_list = new ArrayList<String>();
    ………………
}

创建一个SubjectResults结构体，里面有三个SubjectResult，然后save，成功，但是再把这个SubjectResults从数据库中毒出来，其他字段都是ok的，但是results字段的size为0。

**Comment by xiexin52k** [comment]
因为你是"毒"出来的, 所以这个数据中毒了. 那他的size当然是0;
所以你需要在find函数的参数中额外传递一个 ```true``` 进行解毒才行;

**每一个类型的find()方法，都对应了一个带有isEager参数的方法重载，这个参数相信大家一看就明白是什么意思了，设置成true就表示激进查询，这样就会把关联表中的数据一起查询出来了。**

```java
News news = DataSupport.find(News.class, 1, true);
List<Comment> commentList = news.getCommentList();
```
可以看到，这里并没有什么复杂的用法，也就是在find()方法的最后多加了一个true参数，就表示使用激进查询了。这会将和news表关联的所有表中的数据也一起查出来，那么comment表和news表是多对一的关联，所以使用激进查询一条新闻的时候，那么该新闻所对应的评论也就一起被查询出来了。

**Comment by guolindev** [comment]
感谢 @xiexin52k 的回答，简直是我的救星。

不过楼主的这个用法堪称极其不标准，我完全无法预测这样的代码是否可以正常工作，所以建议还是用更加标准的方式去写。

如果你是要SubjectResults自引用自身，LitePal也是支持的，但是前提是它们的字段都要相同，而不是再定义几个同名的内部类，内部类中拥有不同的字段。

如果你不是想要用自引用的方式，那么就按正常的写法去做一对多关联，把同名内部类提取到外部专门定义一个新的类，让它和SubjectResults形成一对多关联关系，然后再使用 @xiexin52k 同学提供的方法去查询数据即可。

关于LitePal关联关系的定义，可以参考这篇文章 https://blog.csdn.net/guolin_blog/article/details/39207945
