### ISSUE TITLE
数据库更新时，int值=0时，更新不成功呢

### ISSUE THREAD

**Issue by dacaoyuan** [guolindev/LitePal#669]
你好，郭老师，现在用的3.2.2版本，数据库更新时，int类型值=0时，字段更新不成功呢

**Comment by xiexin52k** [comment]
因为java的int默认值就是0, 你int=0的时候, 是不能直接更新字段的. 因为LitePal分不清你是没设置还是要更新. 所以, 对于基本数据类型更新到默认值, 需要调用```setToDefault("字段名")```函数进行设置;

**如果我们想把某一条数据修改成默认值，比如说将评论数修改成0，只是调用updateNews.setCommentCount(0)这样是不能修改成功的，因为即使不调用这行代码，commentCount的值也默认是0。所以如果想要将某一列的数据修改成默认值的话，还需要借助setToDefault()方法。**

**Comment by dacaoyuan** [comment]
感谢郭老师的回复，您的回答解决了我的问题。

**Comment by xiexin52k** [comment]
吓得我打颤... 我可不是郭神. 我只是一个LitePal用户而已....对于LitePal的用法. 建议你去郭神的CSDN上的专题看看. 我觉得郭神应该把专题的地址贴到ReadMe上面去. ReadMe的示例代码太少了....

**Comment by dacaoyuan** [comment]
哈哈，那也谢谢。顺便附上这篇文章的链接吧：https://blog.csdn.net/guolin_blog/article/details/40083685

**Comment by guolindev** [comment]
哈哈，感谢楼上替我回复，回复的非常完美。

这个问题我其实一直在怀疑是不是自己设计的不好，因为重复提这个问题的人太多了，可以参考这条issue https://github.com/guolindev/LitePal/issues/32

当然如果大家有好的建议，比如怎么修改这部分的设计，也欢迎反馈给我，谢谢。
