### ISSUE TITLE
Id 能自己用某个字段使用吗

### ISSUE THREAD

**Issue by Ye83** [guolindev/LitePal#670]
id 的 生成规则是框架自增给生成的吗。
Album albumToUpdate = LitePal.find(Album.class, 1);
find 的id 能自定义字段吗

**Comment by xiexin52k** [comment]
LitePal.where("name=?", "Jay").find(Album.class)
就可以根据指定的字段和值查询结果了
 LitePal.find(Album.class, 1)实际上就是LitePal.where("id=?", "1").find(Album.class)

**Comment by guolindev** [comment]
楼上赞，对LitePal理解的很深刻。

不过这位朋友想问的应该是LitePal可不可以自定义主键，这个问题我思考过很久，我认为开放自定义主键会增加LitePal的使用成本，对一些不太懂数据库设计的朋友，可能返而会和造成更多的问题。比如说开放了自定义主键之后，外键做关联时也要更加小心，而且有些字段其实根本不应该用来做主键，但是部分使用者可能并不知道。

主键的作用是为字段提供唯一性标识，它不能重复，同时也不应该包含任何逻辑意义，因为只要你包含逻辑意义了，那么逻辑就有可能变更，这个时候你就麻烦了，因为主键是不能修改的。

所以综上所述，我仍然还是认为使用自增id作为主键是最好的选择，而且暂时继续不会开放自定义主键这个功能。

**Comment by Ye83** [comment]
谢谢

**Comment by Ye83** [comment]
解答很到位，感谢
