### ISSUE TITLE
LitePal.findBySQL()  中使用 group by 排序没效果

### ISSUE THREAD

**Issue by keaitao0321** [guolindev/LitePal#671]
下面的sql 在工具中使用,可以分组并排序查询,可是在LitePal中,查询的结果可以分组,但是 order by 没有用的,
SELECT * FROM (SELECT * FROM signfacemodel WHERE meetid = '2b151873b4c44f228cf18ce97666cd2a' ORDER BY  signtime  DESC) GROUP BY signuserid  ORDER BY signtime DESC 

需求是:我在一张签到表中,查询人员最近的一次签到数据,根据人员id分组  ps:人员每次签到成功都会保存一次,但是查询需要去重.

**Comment by guolindev** [comment]
太负责的SQL语句具体有没有问题我也没办法帮你定位，但是LitePal.findBySQL()完全就是对原生的rawQuery()做的一层简易封装，返回值也是返回的Cursor，所以LitePal没有对中间数据做任何的转换，不太可能是因为LitePal的原因导致你的group by没效果。

建议你可以使用原生的rawQuery去执行一下同样的SQL语句，我相信一定会得到同样的结果。
