### ISSUE TITLE
列的排序

### ISSUE THREAD

**Issue by YZhaoPeng** [guolindev/LitePal#674]
列的排序能和类中字段的排序一致吗？

**Comment by guolindev** [comment]
不可以的，数据库其中一个非常重要的特性就是行无序性，列无序性，所以不存在列排序这样一种说法。

**Comment by YZhaoPeng** [comment]
> 不可以的，数据库其中一个非常重要的特性就是行无序性，列无序性，所以不存在列排序这样一种表示。

我的意思是创建表的时候，列能不能按照类字段的顺序来创建。
比如用SQL语句创建表时列顺序是 id,name,content，创建完成用工具查看数据库列的顺序也是id,name,content。
而用LitePal创建的好像是乱的，我用getDeclaredFields方法查看类字段时发现他们是固定顺序。

还有能不能兼容一下高版本的数据库文件，比如应用版本是10数据库版本是5备份数据库后，卸载安装1.0版本这个是时候LitePal配置的版本是1，然后导入备份数据库后重启这个时候就会出现错误，还会出现清空数据库的情况。

最好能兼容一下，某些应用会用到备份与恢复功能，而不知道用户会在哪一个版本上恢复，高版本恢复到底版本最好不做清理操作。

备份我是直接备份整个db文件，因为用到了关联（我觉得关联可以支持一下自定义键，关联id不太好）。

希望能考虑一下，备份与恢复的兼容性，兼容非LitePal创建的数据库。
