### ISSUE TITLE
windows可视化表字段排序问题

### ISSUE THREAD

**Issue by af8600** [guolindev/LitePal#676]
在windows使用 SQLiteStudio 可视化查看数据表，发现表中的字段查看有重新被排序过，一般在使用中表中字段顺序与业务逻辑相关，如果重新排序在看起来很不方便，希望此处进行修改。

**Comment by guolindev** [comment]
LitePal在创建表的时候是通过反射获取实体类中的字段，然后基于这些字段来创建列的，所以严格上来说，反射api返回的字段顺序是什么，创建列的时候顺序就是什么，我并没有进行任何特别的排序。

只能说，Java的API中没有办法能够准确获取到你在实体类当中定义字段的顺序。
