### ISSUE TITLE
表字段id不能自定义问题

### ISSUE THREAD

**Issue by jingzhanwu** [guolindev/LitePal#677]
我后端数据的字段 id 不是long型，怎么样把这个id保存到表

**Comment by guolindev** [comment]
LitePal当中id是保留主键，不可自定义，如果服务器当中返回的数据里也有id这个字段，建议通过gson的映射改名成其他更有业务逻辑意义的名称，比如userId，productId等等。

**Comment by jingzhanwu** [comment]
感谢您的建议，已经采用这种方式实现了。
