### ISSUE TITLE
一对多进行关联出现的问题

### ISSUE THREAD

**Issue by lutao2599** [guolindev/LitePal#678]
在进行一对多表进行关联时，一张表更新了名称，会清空另一张表中的数据？请问大神该怎么解决？

**Comment by guolindev** [comment]
一张名更新了名称？ 什么叫更新了名称？

**Comment by lutao2599** [comment]
修改了字段值


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guolindev/LitePal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 下午5:22
收件人:&nbsp;"guolindev/LitePal"<LitePal@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guolindev/LitePal] 一对多进行关联出现的问题 (#678)





 
一张名更新了名称？ 什么叫更新了名称？

**Comment by guolindev** [comment]
额，这个我猜不出来原因，得具体看看代码了。你的表是如何进行关联的，以及你是如何更新数据的。

**Comment by lutao2599** [comment]
解决了，谢谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guolindev/LitePal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 下午5:25
收件人:&nbsp;"guolindev/LitePal"<LitePal@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guolindev/LitePal] 一对多进行关联出现的问题 (#678)





 
额，这个我猜不出来原因，得具体看看代码了。你的表是如何进行关联的，以及你是如何更新数据的。

**Comment by guolindev** [comment]
好的，那我就把这个问题关闭了。

**Comment by yy1378107873** [comment]
> 好的，那我就把这个问题关闭了。
大佬，我也是升级的时候出现相似的问题，是什么原因呢，一张表新增了字段，对应另一张引用它的表数据被清空了
