### ISSUE TITLE
一对多保存List数据获取为null

### ISSUE THREAD

**Issue by androidforzhenghyc** [guolindev/LitePal#679]
1.public class DbLocalRecommend extends LitePalSupport {
    private String saveId;
    private String title;
    private List<DbLocalRecommendListBean> list = new ArrayList<>();
// get set
}
2.public class DbLocalRecommendListBean extends LitePalSupport {

    private DbLocalRecommend recommend;
    ....
// get set
}
3.for (int i = 0; i < data.size(); i++) {
DbLocalRecommend localRecommend = new DbLocalRecommend();
List<T> list = data.get(i);
for(int j = 0; j<list.size();j++){
DbLocalRecommendListBean l = new DbLocalRecommendListBean();
l.setxx(**);
...
l.save();
localRecommend.getList().add(l);
}
localRecommend.save();
}
4.使用 List<DbLocalRecommend> data = LitePal.findAll(DbLocalRecommend.class, true);查询,
然后data里的getList()数据为null

请问是哪里出错了呢

**Comment by guolindev** [comment]
从你贴出来的这部分代码看，我感觉貌似都是正确的。

如果数据查询不出来的话，其实我建议你可以尝试去数据库表里面看一看，到底数据是否都正常存在。

我最近正在开发一个新的开源库，专门是用于查看数据库数据的，你可以用这个开源库尝试定位一下，看看DbLocalRecommend和DbLocalRecommendListBean这两张表里的数据都是否正常。

新的开源库的地址是：https://github.com/guolindev/Glance

**Comment by androidforzhenghyc** [comment]
谢谢大佬回复，我这边找到问题原因了。主要是DbLocalRecommendListBean有个属性id问题，我把id改成其他名称就正常了。之前有碰到过，这次后面才想起来，忘记去github回复了，现在去关闭这个问题下。感恩～




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guolindev/LitePal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 下午5:32
收件人:&nbsp;"guolindev/LitePal"<LitePal@noreply.github.com&gt;;
抄送:&nbsp;"郑恒裕"<531511446@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guolindev/LitePal] 一对多保存List数据获取为null (#679)





 
从你贴出来的这部分代码看，我感觉貌似都是正确的。
 
如果数据查询不出来的话，其实我建议你可以尝试去数据库表里面看一看，到底数据是否都正常存在。
 
我最近正在开发一个新的开源库，专门是用于查看数据库数据的，你可以用这个开源库尝试定位一下，看看DbLocalRecommend和DbLocalRecommendListBean这两张表里的数据都是否正常。
 
新的开源库的地址是：https://github.com/guolindev/Glance

**Comment by androidforzhenghyc** [comment]
问题已解决
