### ISSUE TITLE
表关联的疑问

### ISSUE THREAD

**Issue by lutao2599** [guolindev/LitePal#680]
一对多进行关联后；比如一个文件夹，里面存放了视频和图片，我删除了文件夹，里面的图片和视频会删除吗？

**Comment by guolindev** [comment]
如果你建立的映射关系是，一个文件夹对应子多个视频和图片这样的关联，那么每个视频和图片的数据都会持有文件夹的外键，如果文件夹不存在，这个外键就引用不到，此时就会报错。

LitePal会对使用id形式的删除自动找到所有引用其外键的关联数据，并把这些关联数据也一起删除。但如果你不是使用的id形式删除的文件夹，那么LitePal不会删除关联表的数据，这样视频和图片是不会删除的，但其实这个时候已经属于错误的状态了。所以你需要自己先手动删除这个文件夹下的所有数据，然后再删除这个文件夹。

**Comment by AnJiuZhe** [comment]
这个文件夹的查询出来后，我要用id形式删除它，它的id如何获取呢，kotlin里面好像获取不到啊
