### ISSUE TITLE
多对多，保存数据

### ISSUE THREAD

**Issue by zhongdevin** [guolindev/LitePal#682]
后台返回如下格式：要怎样实现多对多保存数据呢
{
    "foodlist":[
        {
            "food_id":"22",
            "name":"番茄",
            "price":"12.00",
            "cate":"2,3"
        },
        Object{...}
    ],
    "category":[
        {
            "category_id":"1",
            "name":"肉"
        },
        {
            "category_id":"2",
            "name":"青菜"
        },
        {
            "category_id":"3",
            "name":"水果"
        }
    ]
}

**Comment by guolindev** [comment]
这种你只能自己手动解析了，food_id 22这条数据对应的category是2和3，但是这两个category是用逗号隔开的，这是你们自己定义的数据格式，即使gson也没办法帮你自动转换成对象，只能靠你自己手动根据你们定义的规则去解析，别无他法。

**Comment by zhongdevin** [comment]
{
    "foodlist":[
        {
            "food_id":"22",
            "name":"番茄",
            "price":"12.00",
            "cate":"2,3",
            "number":"11",
            "category":[
                Object{...},
                {
                    "category_id":"2",
                    "name":"青菜"
                },
                {
                    "category_id":"3",
                    "name":"水果"
                }
            ]
        },
        Object{...}
    ]
}

> 这种你只能自己手动解析了，food_id 22这条数据对应的category是2和3，但是这两个category是用逗号隔开的，这是你们自己定义的数据格式，即使gson也没办法帮你自动转换成对象，只能靠你自己手动根据你们定义的规则去解析，别无他法。

是像这样吗，但是这样能会有很大的局限性，加入分类没有菜品，那就找不到这个分类了，还有后期不好拓展吧

**Comment by guolindev** [comment]
这不是LitePal的问题，而是你们后台json生成格式的问题呀，我不可能为了你们团队制定的一种json格式去专门给你们做适配，那你们团队用逗号隔开，别人团队用冒号隔开，我怎么能适配的完呢？
