### ISSUE TITLE
请问如何获取保存数据失败时数据库的错误码

### ISSUE THREAD

**Issue by YGRqwerdf** [guolindev/LitePal#683]
怎么在保存数据的时候得到数据库返回的错误信息而不是Save current model failed这一句话，我需要根据错误码做出不同的提示，如code 2067提示重复添加。应为框架有异常处理导致我不能捕获异常信息。

**Comment by guolindev** [comment]
你可以在存储的时候调用 saveThrows 函数，这个函数当保存数据失败的时候会抛出异常堆栈，你根据异常堆栈解析问题就行了。

另外异常捕获是一种补救措施，而不是业务逻辑措施，不要依赖于try catch机制去做任何的业务逻辑处理。
