### ISSUE TITLE
麻烦郭神帮我定位一下是哪出错了，从log来看只能看出数据库操作报错了

### ISSUE THREAD

**Issue by herenxue** [guolindev/LitePal#688]

**Comment by herenxue** [comment]
版本：org.litepal.android:core:1.5.1

出现以下错误：
android.database.CursorWindowAllocationException

Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)

1 org.litepal.exceptions.DataSupportException:Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
2 org.litepal.crud.DataHandler.query(DataHandler.java:151)
3 ......
4 Caused by:
5 android.database.CursorWindowAllocationException:Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
6 android.database.CursorWindow.<init>(CursorWindow.java:108)
7 android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
8 android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
9 android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
10 android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
11 android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
12 org.litepal.crud.DataHandler.query(DataHandler.java:132)
13 org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
14 org.litepal.crud.ClusterQuery.find(ClusterQuery.java:232)
15 org.litepal.crud.ClusterQuery.find(ClusterQuery.java:194)
16 com.flyingwings.cn.robot.service.smarthomeservice.db.dao.DeviceDAO.getDevicesByMac(DeviceDAO.java:21)
17 com.flyingwings.cn.robot.service.smarthomeservice.device.zigbee.tuyaZigbee.TuyaExternalZigbeeDevice$TuyaDeviceListener.onStatusChanged(TuyaExternalZigbeeDevice.java:303)
18 com.tuya.smart.common.o0o00o0o0.onSubDevStatusChanged(TuyaSubDeviceMonitorProxy.java:86)
19 com.tuya.smart.common.o0o00o00o.onEventMainThread(TuyaSubDeviceMonitorManager.java:144)
20 java.lang.reflect.Method.invoke(Native Method)
21 com.tuya.smart.common.o0oo000oo.O000000o(EventBus.java:498)
22 com.tuya.smart.common.o0oo000oo.O000000o(EventBus.java:492)
23 com.tuya.smart.common.o0oo00o0o.handleMessage(HandlerPoster.java:67)
24 android.os.Handler.dispatchMessage(Handler.java:102)
25 android.os.Looper.loop(Looper.java:154)
26 android.app.ActivityThread.main(ActivityThread.java:6121)
27 java.lang.reflect.Method.invoke(Native Method)
28 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
29 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)

**Comment by herenxue** [comment]
使用情况就是我们定义了一个Device表，在这个表的类里面那我们又new 了一些Dao,然后这个类里面还有一些状态监听，当状态发生变化的时候会用Dao去查数据库。

**Comment by af8600** [comment]
掐指一算，应该是内存溢出了

**Comment by guolindev** [comment]
重复问题 https://github.com/guolindev/LitePal/issues/576

**Comment by guolindev** [comment]
因为你用的版本还比较老，1.5.1版本的，这个版本当中还没有废弃二进制存储功能，所以在内存方面是很有可能造成问题的，我甚至怀疑你出现这个问题就是因为使用了二进制数据存储。

从3.1.0版本开始，LitePal不再支持二进制存储功能，原因就是，报的这种错误太多了。

**Comment by herenxue** [comment]
是，我们确实有用到一个二进制的，就是图片经过Base64编码后放进去的，这样使用会有问题么?

**Comment by herenxue** [comment]
按理说不会吧，Base64后是一个String
