### ISSUE TITLE
Litepal.deleteAll清空表后不能保存

### ISSUE THREAD

**Issue by jiangkaifang** [guolindev/LitePal#692]
郭神！
    发现一个有意思的机制。
    假如abc表有100条数据，我通过find查询出所有的数据保存到List集合里，然后用Litepal.deleteAll（abc.class）清空这张表，此时List集合可以正常使用，然后我再把 list 集合 add 100条数据。这个时候无论我是用Litepal.saveAll(list) 还是循环list一条一条save()，最终数据库当中只会保存后面加的这100条数据，之前从数据库中查询出来的那100条并没有被保存到数据库。循环的时候打印每一次save()返回的结果也都是true，但是数据库确只有后面加的那100条数据。

**Comment by guolindev** [comment]
需要清空一下对象的存储状态。

调用model.clearSavedState()能清空单个对象的存储状态。

调用LitePal.markAsDeleted()能清空集合的存储状态。

清空完存储状态之后你再进行保存就可以存储进去了。
