### ISSUE TITLE
LitePal是否支持去重

### ISSUE THREAD

**Issue by FTDShanCai** [guolindev/LitePal#693]
RT，本来想着用 LitePal.select("DISTINCT xxxx") 来去重，最后发现到查询的时候，加了一个id进去。
因为id不一致，所有相当于全查。 
去重的方法是什么呢？

**Comment by guolindev** [comment]
id是LitePal整体工作必须要依赖的一个值，没有id很多功能都会受到影响，所以用LitePal封装的对象api去查询一定会有id值返回，也就导致distinct不会生效。

如果你必须要使用distinct，可以用LitePal提供的原生查询接口，LitePal.rawQuery(sql)，自己写sql语句就可以了。
