### ISSUE TITLE
重置问题

### ISSUE THREAD

**Issue by liuzhenxin2156** [guolindev/LitePal#694]
请教一下，我保存用户信息，退出登录。然后登陆别的账号，怎末能重置数据库呢？就类似Realm数据库。

**Comment by guolindev** [comment]
可以用LitePal.deleteAll()接口把所有表的数据都清空，就相当于重置了（推荐）。
另外也可以使用LitePal.deleteDatabase()接口把数据库直接删除（不推荐），可能会在一些手机上不稳定。
