### ISSUE TITLE
对象内带个数组的话插入会有问题，除list外其他成员变量都可以插入成功，list插入到数据库就始终为null

### ISSUE THREAD

**Issue by hxy1118** [guolindev/LitePal#695]
public class Bean {
       String str1;
       String str2;
      int number;
      List<DataBean> list;
}

**Comment by wu162** [comment]
List里对象所属的那个类也得继承LitePalSupport 并且在litepal,xml里声明才行

**Comment by guolindev** [comment]
楼上说的是多对一关联的情况，另外LitePal也支持存储包装数据类型的List，你得指定一下泛型，不带泛型肯定没法帮你存储呀，谁知道你的List里放的是啥。
具体可以参考这篇文章 https://mp.weixin.qq.com/s/C7nbJXOS9lYPgOda-8Pw0A
