### ISSUE TITLE
'kotlin-android-extensions' is deprecated

### ISSUE THREAD

**Issue by zhouzhuo810** [guolindev/LitePal#696]
The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

**Comment by guolindev** [comment]
The 3.2.3 version should fix it.
Please check it https://github.com/guolindev/LitePal#1-include-library
