### ISSUE TITLE
郭神，请问下我在assets中配置了<storage value="/.db/cache/databases/" />的路径，在android 11 系统中能否正常使用，不受存储分区的影响？

### ISSUE THREAD

**Issue by Traveler1991** [guolindev/LitePal#697]
郭神，请问下我在assets中配置了<storage value="/.db/cache/databases/" />的路径，在android 11 系统中能否正常使用，不受存储分区的影响？

**Comment by guolindev** [comment]
不可能不受分区存储影响，这也是我为什么不建议再将数据库文件存储到sd卡上，甚至未来可能会考虑禁用这个功能的原因。
