### ISSUE TITLE
LitePal.deleteAll(UserEntity::class.java, "id in (?)", delId.joinToString(",")) in 无效

### ISSUE THREAD

**Issue by xiongjiamu** [guolindev/LitePal#701]
LitePal.deleteAll(UserEntity::class.java, "id in (?)", delId.joinToString(","))

这句话不报错 但也不没有效果

**Comment by guolindev** [comment]
这句会被识别为where条件不满足，所以不会删除任何一行数据。
所以不要尝试使用这种语法，为了防止SQL注入，最终执行结果并不会像你想象的那样替换。
