### ISSUE TITLE
保存 一对一 关系，只有一张表里面有数据，另一张表没有数据

### ISSUE THREAD

**Issue by fy310518** [guolindev/LitePal#703]
版本：org.litepal.guolindev:core:3.2.0
重现步骤：
val list = ArrayList<NavBean>()
list.add(NavBean("a", TypeBean()))
list.add(NavBean("B", TypeBean()))
LitePal.saveAll(data)  //使用这个函数  只有一张表里面有数据，另一张表没有数据
//--------------------------------------------------------------------------------------------------
for (nav in list){
       nav.save()  //这样循环 调用单独save函数 没有问题
}

**Comment by guolindev** [comment]
设计就是如此，LitePal不会帮你做级联存储，你自己想存哪些数据就手动去save，但是LitePal会自动帮你做关联。
