### ISSUE TITLE
表不存在时，find能否反回空集合而不是抛出崩溃异常

### ISSUE THREAD

**Issue by lucers** [guolindev/LitePal#705]

**Comment by guolindev** [comment]
LitePal如果吞掉一些异常，对于开发者而言可能反而更难定位问题。表不存在这个是非常严重的一个问题了，因为表也不需要由开发者去创建的，都是LitePal统一创建，如果这个时候还出现表不存在，那说明你的用法已经出现比较大的问题了，这种情况下LitePal不会自己吞掉这个错误，让开发者完全不知晓的。
