### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void org.litepal.parser.LitePalAttr.setDbName

### ISSUE THREAD

**Issue by huangssh** [guolindev/LitePal#707]
1Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.litepal.parser.LitePalAttr.setDbName(java.lang.String)' on a null object reference
2at org.litepal.parser.LitePalAttr.loadLitePalXMLConfiguration(SourceFile:3)
3at org.litepal.parser.LitePalAttr.getInstance(SourceFile:5)
4at org.litepal.util.BaseUtility.changeCase(SourceFile:1)
5at org.litepal.Operator.updateAll(SourceFile:2)
6at org.litepal.LitePal.updateAll(SourceFile:1)

云测平台发现的问题，常见于10.0的设备，由于是偶现不好定位代码

**Comment by guolindev** [comment]
感谢反馈，这种是由于内存回收导致偶现的空指针异常，虽然是可以进行一下非空判断来避免崩溃，但是此时LitePal的状态已经无法正常工作，所以即使避免了崩溃也没有什么太大意义，由于不是逻辑问题导致的错误，就不进行专门的修复了。

**Comment by huangssh** [comment]
> 感谢反馈，这种是由于内存回收导致偶现的空指针异常，虽然是可以进行一下非空判断来避免崩溃，但是此时LitePal的状态已经无法正常工作，所以即使避免了崩溃也没有什么太大意义，由于不是逻辑问题导致的错误，就不进行专门的修复了。

由于多数云测平台会反馈这个bug, 导致我们每个版本迭代被告知要修复这个问题，还是希望郭神有时间可以加个防御，多谢。
