### ISSUE TITLE
3.2.3 存在Cannot resolve symbol 'LitePal' 问题

### ISSUE THREAD

**Issue by mikezhou77** [guolindev/LitePal#712]
郭神你好，我在使用最新版3.2.3遇到了Cannot resolve symbol 'LitePal' 的问题，无法使用LitePal类，使用3.2.2版本就没有此问题

**Comment by qazxcs113** [comment]
。。。引用错库了吧

**Comment by guolindev** [comment]
可以检查一下你的网络是否存在问题，必要情况下建议可以翻下墙，3.2.2可以也有可能是你之前本地有缓存。
