### ISSUE TITLE
Android10.0文件沙盒机制,导致litepal无法使用了,希望能进行适配

### ISSUE THREAD

**Issue by SJLBenjamin** [guolindev/LitePal#713]
Android10.0通过文件沙盒机制,无法通过读取litepal.xml的配置的文件存储路径,进行文件存储,请问此处可以进行兼容修改吗

**Comment by guolindev** [comment]
文件沙盒机制对litepal并没有任何影响，litepal.xml是放到assets当中的，与沙盒机制无关，所以可能还是你的用法哪里出了问题。
