### ISSUE TITLE
将非必要字段剔除

### ISSUE THREAD

**Issue by zhangjianwei1** [guolindev/LitePal#714]
请问一下，如果我在一个extends  LitePalSuppor的对象里新增了一个字段default_value，但是我不想将这个字段添加到表里，需要怎么操作

**Comment by qazxcs113** [comment]
那你还是新建个类吧。。。不想重复写对象就继承。

**Comment by guolindev** [comment]
在字段上声明 @Column(ignore = true) 即可。
