### ISSUE TITLE
数据查询/保存等操作异步不调用

### ISSUE THREAD

**Issue by vanzh** [guolindev/LitePal#718]
litepal  3.0.0
我在使用过程中出现了 保存/查询数据没有回调的情况。
目前数据库表定义如下
`
class A extends LitePalSupport{
B b;
C c;

 @Override
    public boolean save() {
         boolean save = super.save();
         b.save();
         c.save();
         return save;
   }
}

class B extends LitePalSupport{
}

class C extends LitePalSupport{
}

`

saveAsync().listen() 来保存，在保存前、回调后分别埋点上传，oppo vivo两种手机数据差太多，保存前埋点上传100次，保存回调后上报只有80次左右，友盟统计没有与之相关的崩溃及ANR,   即使保存失败，那么也会有回调，也会上报回调后的埋点。

那么在那种情况会导致异步不回调呢？   有没有可能在数据库初始化时出现了问题？

同样的保存逻辑，对新老用户进行分析，呈现很大的差异性，保存成功率 = 保存后埋点/保存前埋点 ，发现新用户不到70%， 而老用户却有97%以上。 

目前这个问题看了好几天，找不到解决问题方向，来这里请教一下

**Comment by guolindev** [comment]
LitePal的异步API并不稳定，只是一个简单的线程开启，没有执行完成保障，也没有并发控制，所以在新版里面已经废弃了所有的异步API。

至于不调用的情况我只能说有很多，因为如果你没有阻止用户去进行其他操作，那么在异步存储数据的时候，用户可能去关闭页面，回到桌面，强杀应用，各种情况都有可能。

所以这个情况我也无法保证，而且已经不再建议使用异步API了。
