### ISSUE TITLE
索引没有办法设置升序还是降序排列

### ISSUE THREAD

**Issue by SJLBenjamin** [guolindev/LitePal#719]
郭神,索引只能选择开启或者关闭,没有办法设置是升序还是降序

**Comment by guolindev** [comment]
额，你可能是对索引的理解还有些偏差，索引的作用可以参考这篇文章 https://guolin.blog.csdn.net/article/details/107744242

查询结果的升序还是降序可以用asc和desc来指定，而不是索引。
