### ISSUE TITLE
建议字段的取值与赋值优先调用对应的getter和setter方法

### ISSUE THREAD

**Issue by xiexin52k** [guolindev/LitePal#720]
LitePal内部对字段的赋值与取值, 都是通过反射调用 ```objectField.set(object,` value);``` 与 ```objectField.get(object);```

这样导致的结果就是无法对字段进行一些自定义的特殊操作, 比如给字段进行其他算法的加密等等. 虽然可以重写LitePalSupport函数进行曲线救国, 但是这样始终不够方便, 也容易出错.

所以我建议是优先调用字段的getter和setter方法. 在没有找到方法的情况下再直接操作字段.

**Comment by guolindev** [comment]
LitePal这样设计是有原因的，可以参考这篇文章 https://mp.weixin.qq.com/s/-_TrZ4-KiJgqwOxOUDqppg
