### ISSUE TITLE
updateAll()修改无效，报0

### ISSUE THREAD

**Issue by xxdc** [guolindev/LitePal#721]
![image](https://user-images.githubusercontent.com/17997682/113271531-38b25000-930d-11eb-909b-ff4cc9f0eb39.png)

**Comment by xiexin52k** [comment]
1. 在update之前, 数据是不是已经保存好了?
2. 条件是否符合? 假设update条件是name='张三', 那么你数据库中是否已经存在相关数据?

**Comment by guolindev** [comment]
感谢楼上解答，是正解。
