### ISSUE TITLE
进度监听

### ISSUE THREAD

**Issue by zhangjianwei1** [guolindev/LitePal#722]
您好，请问下有进度监听么，因为APP需求，首次进入的时候需要添加大量的数据到表中，这时候会使手机卡顿无响应，想加个进度监听来使用户在这段时间不能操作这个AP

**Comment by guolindev** [comment]
这个属于业务逻辑，你可以自己加。比如开个线程执行数据添加操作，然后你用一个变量来记录是否添加完成，没有完成之前不让操作APP就行了。

**Comment by zhangjianwei1** [comment]
我的意思是我怎么判断数据已经添加完毕

**Comment by guolindev** [comment]
你调用了添加数据的api，api的下一行执行的时候，数据就已经添加完毕了呀。
