### ISSUE TITLE
如何添加多对多关系的额外属性

### ISSUE THREAD

**Issue by sbwww** [guolindev/LitePal#728]
比如我有一个菜品 `Dish` 类和一个食材 `Food`类，这二者在多对多的关系中还有一个数量 `num` 的额外属性，即菜品消耗多少份这种食材
请问如何使用 LitePal 表示该额外属性呢？当建立多对多关系时，需要为关系表也建立一个类吗？

**Comment by xiexin52k** [comment]
既然是多对多了, 那么Dish依赖了List<Food>, 难道这个集合的size不能表示消耗多少食材吗?
