### ISSUE TITLE
排序

### ISSUE THREAD

**Issue by zhangjianwei1** [guolindev/LitePal#741]
order是排序字段，当order是int类型的时候排序正常，但是order是string类型的时候，查询拿到的顺序不对，请问一下当排序字段为string的时候怎么排序

**Comment by xiexin52k** [comment]
String有好几种
1. 标准时间格式化的String
2. 纯数字的String
这些都是由数据库转换成数值类进行大小排序
如果是随机String, 则按照hashCode大小排序

不过可以通过指定 COLLATE 方式按照特定的格式排序(COLLATE 用法请自行上网查资料)
```
ORDER BY title COLLATE LOCALIZED ASC
```
以上语句表示根据区域自然语言排序. 会按照 数字>字母>中文拼音首字母排序
以上语句转换成LitePal就是
```
orderBy("title=? COLLATE LOCALIZED ASC", title)
```

**Comment by guolindev** [comment]
感谢楼上，比我更专业。
