### ISSUE TITLE
无法保存byte[]

### ISSUE THREAD

**Issue by DarkGown** [guolindev/LitePal#746]
save() 保存成功，
再查询其他数据都有byte是null。

**Comment by xiexin52k** [comment]
https://mp.weixin.qq.com/s/IlaTEcC8qEIWAcx2GDY1wA

1. 二进制数据存储

这个功能是我非常不应该增加的一个功能，因为数据库本身就不适合存储二进制数据。为什么呢？二进制数据通常都会很大，一张高清图片可能就会占据几M的内存，将这种数据存放到数据库中是比较危险的，很可能会引发刚才提到的CursorWindows的错误导致程序崩溃，这就让LitePal变得不够稳定。

那么又有多少开发者会有向数据库中存储二进制数据的需求呢？这个真的很少，因为大部分人的做法都是将二进制数据以文件的形式存储到本地，然后在数据库中存储一条文件的路径就可以了。这种做法更加科学安全，也不会给数据库增加额外的压力。

因此，从LitePal 3.1.0版本开始，将不再支持存储和读取二进制数据功能（实体类中定义的byte数组字段将被忽略），此项变更立即生效，如果有用到这部分功能的朋友，请在升级之前完成修改。

**Comment by guolindev** [comment]
从3.1.0版本开始，LitePal不再支持二进制存储功能，原因楼上已经贴出来了。

如果一定要使用二进制存储功能，可以考虑3.1.0以下的版本。
