### ISSUE TITLE
where id < ? and id > ?怎么写

### ISSUE THREAD

**Issue by zhaoxianshen** [guolindev/LitePal#751]

**Comment by zhaoxianshen** [comment]
LitePal.where("id>? and id<?", "start%" ,"end%").find(Message.class) 不对

**Comment by xiexin52k** [comment]
LitePal的id固定设置为表主键, 所以你要搜索id条件值只能传数字. 
使用Integer.toString, String.valueOf, 或者 数字+"" 形式传参数
例如 LitePal.where("id>? and id<?", "0" ,"10").find(Message.class)

**Comment by guolindev** [comment]
楼上正解
