### ISSUE TITLE
字段类型问题：实体类是boolean，litepal.xml映射后，实际表是Integer类型

### ISSUE THREAD

**Issue by DodoSpringLove** [guolindev/LitePal#769]
字段类型问题：实体类是boolean，litepal.xml映射后，实际表是Integer类型

**Comment by amosxb** [comment]
这个是这样的，所有查询的时候填0或者1

**Comment by guolindev** [comment]
楼上已经替我解答了，谢谢，因为SQLite里面是没有boolean这种类型的，只能转换成数字来存储
