### ISSUE TITLE
org.litepal.exceptions.InvalidAttributesException: the version in litepal.xml is earlier than the current version

### ISSUE THREAD

**Issue by GongZiZhang** [guolindev/LitePal#771]
友盟统计上报有大量的：org.litepal.exceptions.InvalidAttributesException: the version in litepal.xml is earlier than the current version
这个版本我是新加入的LitePal库，所以按理说之前是没有任何版本号的，何来xml里的版本号比当前版本低？搞不清楚问题在哪，有大佬可以解答下么

**Comment by GongZiZhang** [comment]
根据对接部分用户的手机，发现打印出来的extraKeyName为null ,但SharedUtil.getLastVersion(extraKeyName)获取到的数值居然是统一的36

**Comment by guolindev** [comment]
extraKeyName为null是正常的，只要你使用的是默认数据库，extraKeyName都是null。

SharedUtil.getLastVersion(extraKeyName)获取到的值是36，那就说明就是36，可能是你们之前发出去的什么版本用过LitePal，你不知道，当时生成了一个版本号，就一直记录在这些老用户的手机上了。

解决方法也很简单，你把版本号改成36以上就可以了，这个数字没啥意义，没必要非从1开始。

**Comment by GongZiZhang** [comment]
> 

可以肯定之前版本没有用过LitePal，因为这个app一开始就是由我开发的，而且是部分用户会出现这种情况，并不是所有的用户
