### ISSUE TITLE
gson id冲突

### ISSUE THREAD

**Issue by ruancaipu** [guolindev/LitePal#772]
private long id;
    private int unfinishCount;//未完成数量
    private int finishCount;//已完成数量
    @SerializedName("id")
    private String patid;

 Caused by: java.lang.IllegalArgumentException: class com.fgtd.yzsj.patrol.PatrolListBean declares multiple JSON fields named id

**Comment by guolindev** [comment]
@SerializedName("id") 
这一行，改成非id字样的其它名字即可。

**Comment by ruancaipu** [comment]
patid 接口返回的名字本身就是id,所以我才用SerializedName重命名的啊。
@ SerializedName("xid")
private String id
是这样么？

**Comment by ILoveYouCC** [comment]
> patid 接口返回的名字本身就是id,所以我才用SerializedName重命名的啊。 @ SerializedName("xid") private String id 是这样么？

大佬，后面这个咋个解决的啊。
